openapi: "3.0.1"
info:
  title: JSON Web Token API
  description: Generates access and refresh JWT
  contact:
    name: API Support
    email: dmitrym.dev@websm.io
  version: 1.0.0

servers:
  - url: http://jwt-sign-server.websm.io
    description: production server
  - url: http://jwt-sign-server.websm.io/api/{version}
    description: production server
    variables:
      version:
        description: api version
        default: v1

paths:
  /generator:
    $ref: 'components/paths/generator.yaml'
  /refresher:
    $ref: 'components/paths/refresher.yaml'
  /verifier:
    $ref: 'components/paths/verifier.yaml'
